# Generated by Django 4.2.1 on 2023-05-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(choices=[('python', 'Python'), ('JAVA', 'Java'), ('javascript', 'Javascript')], default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
