# Generated by Django 4.2.1 on 2023-05-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_tag_type_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.BooleanField(choices=[('python', 'Python'), ('JAVA', 'Java'), ('javascript', 'Javascript')], null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.tag'),
        ),
    ]
